functionsDirectory = "/root/workspace/black-car-service/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "/root/workspace/black-car-service"
publishOrigin = "default"
functions = "/root/workspace/black-car-service/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]